# Generated by Django 4.0.6 on 2022-07-09 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_courses_course_rename_subjects_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name']},
        ),
    ]
